# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  postgresql: 9.4
  firefox: "49.0"

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
    - env: REQUIREMENTS=devel E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio"
    - env: REQUIREMENTS=devel E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

before_cache:
  - "rm -f $HOME/selenium/geckodriver-v0.11.1-linux32.tar.gz"

cache:
  pip: true
  directories:
  - $HOME/selenium

services:
  - mysql
  - postgresql
  - redis

env:
  - REQUIREMENTS=lowest E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=lowest E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio"
  - REQUIREMENTS=lowest E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=release E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio"
  - REQUIREMENTS=release E2E_WEBDRIVER_BROWSERS="Firefox" EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=devel E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=devel E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio"
  - REQUIREMENTS=devel E2E_WEBDRIVER_BROWSERS="" EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "if [ ! -f $HOME/selenium/geckodriver ]; then wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux32.tar.gz -P $HOME/selenium; tar xvfz $HOME/selenium/geckodriver-v0.11.1-linux32.tar.gz -C $HOME/selenium; fi"
  - "PATH=$PATH:$HOME/selenium"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "sleep 3" # give xvfb some time to start

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: k3KDxk1xxZXxgF6mgv/0kKgMSchsY7l+iVecNqth90ABaNDKyGQa43UY0qS4W5HGqTNOTZPcMyt2SoFSjCzMP++LqWe/7EghH5yA7GQW+u4N9wnz+QYlWbuPJcRq/gaWCYGVvD8EhGGLHVTj7BIolvIplz4f9+KgneR9PTdRdhA0MOm1oIqh8JZqZc7d8oJQwWSt0kIBwy2Gam73et0CjMlk6/R/WM6n/lgs/5R3k8kAvEYBgLmiTi01KuyU/rBSXe+SItQMrHWoS1dcJV+ZTxl3F2OkQS1dCs8d+7V1jGnA8bXAG6psP7hW9/TBLMfvDNbaIvJIUWZdkjU+ft3jzBMjVfeHr9pA+3yDtRzVLQ1HKcoZgh0+OjK3O5FzMr95Ato0VA1PR7m1grb7IU6lCz0roukZvwJ0JuhhJlEkbrr+6L5H+GAUKmY21yxbyZtfZB8itiHHY17Bv8x3eOFM8dtlI3ZqJ640rQbLHdtZjKVN0UcwvY1gHE5XepAI4AVvmQU9Kf2hKtUe1k/lJKsNuWzNI/2Q2eY15F4Bq4ENyGtzfhQJTthHgoFecjjstosg0Zg1HZG13aZDmb7W3CRxUpCIiSkceyg+ov7ddsdjSAwWP1Q3fEwQ/cvpWXKiPyP4B6P6EtLnsQdaC4YiIhguZ5uBgZA2HDmCzQ7JIGk/kbg=
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = release
